name: Bug Report
description: Send a bug report
title: "Untitled bug report"
labels: [bug]
assignees:
  - MrHugger
body:
  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft version
      description:  "What Minecraft version did you experience this bug on?"
      multiple: false
      options:
        - 1.21.x
        - 1.19.x-1.20.x
    validations:
      required: true
  - type: input
    id: other_mods
    attributes:
      label: Other worldgen mods/dps
      description: "What other mods/datapacks for world generation are you using?"
      placeholder: For example Terralith, Incendium and others
    validations:
      required: false
  - type: textarea
    id: the_problem
    attributes:
      label: What went wrong?
      description: "What did you expect to happen, and what happened instead?"
      placeholder: Please provide as much information as you can
    validations:
      required: true